project:
  type: website
  output-dir: docs

website:
  title: "MED3007 V25"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: get_started/get_started.qmd
        text: Get Started
      #- href: lecture_notes/overview.qmd
      #  text: Lecture notes
      - href: lab/overview.qmd
        text: Lab and Code
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/ocbe-uio/course_med3007
  page-navigation: true

format:
  html:
    theme: flatly
    # css: styles.css
    toc: true

editor: source

