---
title: "MED3007: Statistical Principles in Genomics"
---

# Welcome!

This is the course website for **MED3007: Statistical Principles in Genomics** at the Faculty of Medicine, University of Oslo. 

The course website is developed by the instructors of the course, hosted for free and public accessible on Github. Course material can be found in the [github repository](https://github.com/ocbe-uio/course_med3007).

### Structure

* [Get Started](https://ocbe-uio.github.io/course_med3007/get_started/get_started.html) provides some information about software installation, data download and code.
* [R Lab and Code](https://ocbe-uio.github.io/course_med3007/lab/overview.html) hosts the lab session exercises and code.


::: callout-note
## Official course webpage

Please refer to the [official course page](https://www.uio.no/studier/emner/medisin/med/MED3007/) by University of Oslo for information related to **application, evaluation and other administrative matters**.

:::

### Preparation before the course starts

You should have R installed on your computer before the course. More on preparation please read [here](https://ocbe-uio.github.io/course_med3007/get_started/get_started.html).

If you have trouble setting it up with your own laptop, you can also use the PC in the PC lab.


# Schedule

You can find the **time and place** on the [official course schedule](https://www.uio.no/studier/emner/medisin/med/MED3007/v25/timeplan/index.html) at the University of Oslo course website. 

If there is a conflict of information, please refer to the official schedule.

### Day 1

|     Time      |                 Topic                |  Course material  |
|:-------------:|:------------------------------------:|:-----------------:|
| 9:00 - 9:45   | Introduction to the course | [Lecture](lecture_notes/MED3007_Lecture0.pdf)                  |
| 10:00 - 11:30  | Lab: Introduction to R and Rstudio  | [Lab: intro to R](lab/lab_day1_intro.qmd), [Code](https://github.com/ocbe-uio/course_med3007/blob/main/lab/code/MED3007_Lab0_intro_r.R) |
| 13:00 - 14:00  | Data screening and multiple testing   | [Lecture](lecture_notes/MED3007_Lecture1.pdf)  |
| 14:00 - 16:00  | Q&A | |



### Day 2

|     Time      |                 Topic                |  Course material  |
|:-------------:|:------------------------------------:|:-----------------:|
| 9:00 - 9:45   | Lab: Data screening and multiple testing  | |
| 10:00 - 11:30  | Exercises  | [Lab: multiple testing](https://ocbe-uio.github.io/course_med3007/lab/lab_day2_testing.html), [Code](https://github.com/ocbe-uio/course_med3007/blob/main/lab/code/MED3007_Lab1.R), [Code (solution)](https://github.com/ocbe-uio/course_med3007/blob/main/lab/code/MED3007_Lab1_exercise_solution.R)   |
| 13:00 - 14:00  | Data visualization, dimensional reduction | [Lecture](lecture_notes/MED3007_Lecture2.pdf)   |
| 14:00 - 16:00  | Q&A | |



### Day 3

|     Time      |                 Topic                |  Course material  |
|:-------------:|:------------------------------------:|:-----------------:|
| 9:00 - 9:45   | Lab: Data visualization, dimensional reduction |  |
| 10:00 - 11:30  | Exercises  |[Lab: PCA](https://ocbe-uio.github.io/course_med3007/lab/lab_day3_pca.html), [Code](https://github.com/ocbe-uio/course_med3007/blob/main/lab/code/MED3007_Lab2_pca.R)  |
| 13:00 - 14:00  | Clustering   |  [Lecture](lecture_notes/MED3007_Lecture3.pdf)  |
| 14:00 - 16:00  | Q&A | |

### Day 4

|     Time      |                 Topic                |  Course material  |
|:-------------:|:------------------------------------:|:-----------------:|
| 9:00 - 9:45   | Lab: Clustering and heatmaps |   |
| 10:00 - 11:30  | Exercises  | [Lab: clustering](https://ocbe-uio.github.io/course_med3007/lab/lab_day4_clustering.html), [Code](https://github.com/ocbe-uio/course_med3007/blob/main/lab/code/MED3007_Lab3_clustering.R) |
| 13:00 - 14:00  | Take-home exam simulation   | [Exam material](https://github.com/ocbe-uio/course_med3007/tree/main/exam) |
| 14:00 - 16:00  | Q&A | |


Papers

* [Paper I: Cappelletti 2022](lecture_notes/CappellettiEtAL_2022.pdf)
* [Paper II: Ankill 2022](lecture_notes/AnkillEtAl_2022.pdf)

